FROM python:3.10
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app ./app
COPY ./tests ./tests
COPY ./alembic ./alembic
COPY ./alembic.ini ./
COPY pytest.ini ./
RUN mkdir -p /app/data
CMD ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]
