"""add cancelacion fields to factura

Revision ID: 01639b947ac0
Revises: d01934cde1b6
Create Date: 2025-08-28 18:19:01.730125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01639b947ac0"
down_revision: Union[str, Sequence[str], None] = "d01934cde1b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facturas", sa.Column("motivo_cancelacion", sa.String(length=2), nullable=True)
    )
    op.add_column(
        "facturas",
        sa.Column("folio_fiscal_sustituto", sa.String(length=36), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("facturas", "folio_fiscal_sustituto")
    op.drop_column("facturas", "motivo_cancelacion")
    # ### end Alembic commands ###
