"""add tasa_impuesto to presupuesto_detalles

Revision ID: 0316fa17dff7
Revises: 7c349df82af7
Create Date: 2025-11-20 22:39:00.556105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0316fa17dff7'
down_revision: Union[str, Sequence[str], None] = '7c349df82af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presupuesto_detalles', sa.Column('tasa_impuesto', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.08'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presupuesto_detalles', 'tasa_impuesto')
    # ### end Alembic commands ###
