"""add_geolocation_to_cliente

Revision ID: 147723f0d03a
Revises: c0d104bf09e0
Create Date: 2025-10-07 18:40:09.462856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "147723f0d03a"
down_revision: Union[str, Sequence[str], None] = "c0d104bf09e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clientes", sa.Column("latitud", sa.Float(), nullable=True))
    op.add_column("clientes", sa.Column("longitud", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clientes", "longitud")
    op.drop_column("clientes", "latitud")
    # ### end Alembic commands ###
