"""Make usuario_id nullable in presupuesto_eventos

Revision ID: 1b9ad6ebaca0
Revises: 0316fa17dff7
Create Date: 2025-11-21 21:04:21.051442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9ad6ebaca0'
down_revision: Union[str, Sequence[str], None] = '0316fa17dff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuesto_detalles', 'tasa_impuesto',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('presupuesto_eventos', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuesto_eventos', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('presupuesto_detalles', 'tasa_impuesto',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=sa.text('0.08'),
               existing_nullable=False)
    # ### end Alembic commands ###
