"""Base schema

Revision ID: 1f3c51757056
Revises: 180ac1a4efca
Create Date: 2025-07-28 19:11:59.161076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f3c51757056"
down_revision: Union[str, Sequence[str], None] = "180ac1a4efca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productos_servicios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("clave_producto", sa.String(length=20), nullable=False),
        sa.Column("clave_unidad", sa.String(length=20), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("valor_unitario", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("stock_actual", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("stock_minimo", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("unidad_inventario", sa.String(length=20), nullable=True),
        sa.Column("ubicacion", sa.String(length=100), nullable=True),
        sa.Column("requiere_lote", sa.Boolean(), nullable=True),
        sa.Column(
            "creado_en", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "descripcion", name="uq_empresa_descripcion"),
    )
    op.alter_column(
        "empresas",
        "nombre_comercial",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "empresas",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "empresas",
        "actualizado_en",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "empresas",
        "actualizado_en",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "empresas",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "empresas",
        "nombre_comercial",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_table("productos_servicios")
    # ### end Alembic commands ###
