"""Add usuario model

Revision ID: 2d2bc3db3f3e
Revises: 16ba07feec40
Create Date: 2025-12-10 11:32:18.700114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2bc3db3f3e'
down_revision: Union[str, Sequence[str], None] = '16ba07feec40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('rol', sa.Enum('ADMIN', 'SUPERVISOR', name='rolusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
