"""Lo que cambió

Revision ID: 37985e7e6749
Revises: 1f3c51757056
Create Date: 2025-07-28 19:12:13.668319

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "37985e7e6749"
down_revision: Union[str, Sequence[str], None] = "1f3c51757056"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
