"""Cliente: agregar campos de dirección detallada y pagos

Revision ID: 3ab2e77b659d
Revises: 37985e7e6749
Create Date: 2025-07-30 22:48:18.641559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab2e77b659d'
down_revision: Union[str, Sequence[str], None] = '37985e7e6749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('calle', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('numero_exterior', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('numero_interior', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('colonia', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('codigo_postal', sa.String(length=10), nullable=False))
    op.add_column('clientes', sa.Column('dias_credito', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('dias_recepcion', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('dias_pago', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('tamano', sa.String(length=15), nullable=True))
    op.add_column('clientes', sa.Column('actividad', sa.String(length=15), nullable=True))
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('clientes_numero_identificacion_key'), 'clientes', type_='unique')
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'tipo_identificacion')
    op.drop_column('clientes', 'numero_identificacion')
    op.drop_column('clientes', 'codigo_postal_domicilio')
    op.alter_column('empresas', 'contrasena',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresas', 'contrasena',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('clientes', sa.Column('codigo_postal_domicilio', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('numero_identificacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('tipo_identificacion', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('clientes_numero_identificacion_key'), 'clientes', ['numero_identificacion'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('clientes', 'actividad')
    op.drop_column('clientes', 'tamano')
    op.drop_column('clientes', 'dias_pago')
    op.drop_column('clientes', 'dias_recepcion')
    op.drop_column('clientes', 'dias_credito')
    op.drop_column('clientes', 'codigo_postal')
    op.drop_column('clientes', 'colonia')
    op.drop_column('clientes', 'numero_interior')
    op.drop_column('clientes', 'numero_exterior')
    op.drop_column('clientes', 'calle')
    # ### end Alembic commands ###
