"""add logo to empresa

Revision ID: 5f829bd46ac1
Revises: bf84cfb03f50
Create Date: 2025-08-19 18:56:19.453997

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5f829bd46ac1"
down_revision: Union[str, Sequence[str], None] = "bf84cfb03f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
