"""add observaciones a facturas

Revision ID: 69d1c4e01ed9
Revises: ba1a87131130
Create Date: 2025-08-13 17:26:20.297827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d1c4e01ed9'
down_revision: Union[str, Sequence[str], None] = 'ba1a87131130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('facturas_detalle', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('facturas_detalle', sa.Column('requiere_lote', sa.Boolean(), nullable=True))
    op.add_column('facturas_detalle', sa.Column('lote', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas_detalle', 'lote')
    op.drop_column('facturas_detalle', 'requiere_lote')
    op.drop_column('facturas_detalle', 'tipo')
    op.drop_column('facturas', 'observaciones')
    # ### end Alembic commands ###
