"""Add missing CFDI fields to Pago model

Revision ID: 750321b499f4
Revises: b7e05f0ad483
Create Date: 2025-09-24 04:14:38.318425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "750321b499f4"
down_revision: Union[str, Sequence[str], None] = "b7e05f0ad483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pagos", sa.Column("motivo_cancelacion", sa.String(length=2), nullable=True)
    )
    op.add_column(
        "pagos",
        sa.Column("folio_fiscal_sustituto", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "pagos", sa.Column("no_certificado", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "pagos", sa.Column("no_certificado_sat", sa.String(length=20), nullable=True)
    )
    op.add_column("pagos", sa.Column("sello_cfdi", sa.Text(), nullable=True))
    op.add_column("pagos", sa.Column("sello_sat", sa.Text(), nullable=True))
    op.add_column(
        "pagos", sa.Column("rfc_proveedor_sat", sa.String(length=13), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pagos", "rfc_proveedor_sat")
    op.drop_column("pagos", "sello_sat")
    op.drop_column("pagos", "sello_cfdi")
    op.drop_column("pagos", "no_certificado_sat")
    op.drop_column("pagos", "no_certificado")
    op.drop_column("pagos", "folio_fiscal_sustituto")
    op.drop_column("pagos", "motivo_cancelacion")
    # ### end Alembic commands ###
