"""feat: add presupuestos tables

Revision ID: 7c349df82af7
Revises: bb652289eaaf
Create Date: 2025-11-18 20:34:50.616744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c349df82af7'
down_revision: Union[str, Sequence[str], None] = 'bb652289eaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'CADUCADO', 'FACTURADO', name='estado_presupuesto_enum'), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('condiciones_comerciales', sa.Text(), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('firma_cliente', sa.String(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index(op.f('ix_presupuestos_cliente_id'), 'presupuestos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_presupuestos_empresa_id'), 'presupuestos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_presupuestos_responsable_id'), 'presupuestos', ['responsable_id'], unique=False)
    op.create_table('presupuesto_adjuntos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presupuesto_id', sa.UUID(), nullable=False),
    sa.Column('archivo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('fecha_subida', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_adjuntos_presupuesto_id'), 'presupuesto_adjuntos', ['presupuesto_id'], unique=False)
    op.create_table('presupuesto_detalles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presupuesto_id', sa.UUID(), nullable=False),
    sa.Column('producto_servicio_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('costo_estimado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('impuesto_estimado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margen_estimado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['productos_servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_detalles_presupuesto_id'), 'presupuesto_detalles', ['presupuesto_id'], unique=False)
    op.create_index(op.f('ix_presupuesto_detalles_producto_servicio_id'), 'presupuesto_detalles', ['producto_servicio_id'], unique=False)
    op.create_table('presupuesto_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presupuesto_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.Enum('CREADO', 'EDITADO', 'ENVIADO', 'VISTO', 'ACEPTADO', 'RECHAZADO', 'FACTURADO', name='accion_presupuesto_enum'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_eventos_presupuesto_id'), 'presupuesto_eventos', ['presupuesto_id'], unique=False)
    op.create_index(op.f('ix_presupuesto_eventos_usuario_id'), 'presupuesto_eventos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuesto_eventos_usuario_id'), table_name='presupuesto_eventos')
    op.drop_index(op.f('ix_presupuesto_eventos_presupuesto_id'), table_name='presupuesto_eventos')
    op.drop_table('presupuesto_eventos')
    op.drop_index(op.f('ix_presupuesto_detalles_producto_servicio_id'), table_name='presupuesto_detalles')
    op.drop_index(op.f('ix_presupuesto_detalles_presupuesto_id'), table_name='presupuesto_detalles')
    op.drop_table('presupuesto_detalles')
    op.drop_index(op.f('ix_presupuesto_adjuntos_presupuesto_id'), table_name='presupuesto_adjuntos')
    op.drop_table('presupuesto_adjuntos')
    op.drop_index(op.f('ix_presupuestos_responsable_id'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_empresa_id'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_cliente_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
