"""add_xml_pdf_to_egreso

Revision ID: 97ee9120af15
Revises: a086d3a02bef
Create Date: 2026-01-16 00:28:29.708299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ee9120af15'
down_revision: Union[str, Sequence[str], None] = 'a086d3a02bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('archivo_xml', sa.String(), nullable=True))
    op.add_column('egresos', sa.Column('archivo_pdf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos', 'archivo_pdf')
    op.drop_column('egresos', 'archivo_xml')
    # ### end Alembic commands ###
