"""Add fecha_emision to Pago

Revision ID: a086d3a02bef
Revises: cfa7eee2e18f
Create Date: 2026-01-15 05:29:47.718537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a086d3a02bef'
down_revision: Union[str, Sequence[str], None] = 'cfa7eee2e18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pago_documentos_relacionados', 'impuestos_dr',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('pagos', sa.Column('fecha_emision', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'fecha_emision')
    op.alter_column('pago_documentos_relacionados', 'impuestos_dr',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
