"""Fix EmailConfig empresa_id type to UUID

Revision ID: b7e05f0ad483
Revises: f00a9666ab86
Create Date: 2025-09-17 23:35:10.468972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7e05f0ad483"
down_revision: Union[str, Sequence[str], None] = "f00a9666ab86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("smtp_server", sa.String(), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("smtp_user", sa.String(), nullable=False),
        sa.Column("smtp_password", sa.String(), nullable=False),
        sa.Column("from_address", sa.String(), nullable=False),
        sa.Column("from_name", sa.String(), nullable=True),
        sa.Column("use_tls", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_configs_empresa_id"),
        "email_configs",
        ["empresa_id"],
        unique=True,
    )
    op.create_index(op.f("ix_email_configs_id"), "email_configs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_configs_id"), table_name="email_configs")
    op.drop_index(op.f("ix_email_configs_empresa_id"), table_name="email_configs")
    op.drop_table("email_configs")
    # ### end Alembic commands ###
