"""add facturas

Revision ID: ba1a87131130
Revises: 9c73aa993914
Create Date: 2025-08-12 17:51:31.914304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1a87131130'
down_revision: Union[str, Sequence[str], None] = '9c73aa993914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=1), nullable=False),
    sa.Column('forma_pago', sa.String(length=3), nullable=True),
    sa.Column('metodo_pago', sa.String(length=3), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=3), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lugar_expedicion', sa.String(length=5), nullable=True),
    sa.Column('condiciones_pago', sa.Text(), nullable=True),
    sa.Column('cfdi_relacionados_tipo', sa.String(length=2), nullable=True),
    sa.Column('cfdi_relacionados', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('impuestos_trasladados', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('impuestos_retenidos', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('estatus', sa.String(length=15), nullable=False),
    sa.Column('cfdi_uuid', sa.String(length=36), nullable=True),
    sa.Column('fecha_timbrado', sa.DateTime(), nullable=True),
    sa.Column('no_certificado', sa.String(length=20), nullable=True),
    sa.Column('no_certificado_sat', sa.String(length=20), nullable=True),
    sa.Column('sello_cfdi', sa.Text(), nullable=True),
    sa.Column('sello_sat', sa.Text(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('fecha_cobro', sa.DateTime(), nullable=True),
    sa.Column('status_pago', sa.String(length=10), nullable=False),
    sa.Column('xml_path', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'serie', 'folio', name='uq_fact_serie_folio_por_empresa')
    )
    op.create_index(op.f('ix_facturas_cliente_id'), 'facturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_facturas_empresa_id'), 'facturas', ['empresa_id'], unique=False)
    op.create_index('ix_facturas_fechas_pago', 'facturas', ['fecha_pago', 'fecha_cobro'], unique=False)
    op.create_index('ix_facturas_serie_folio', 'facturas', ['serie', 'folio'], unique=False)
    op.create_index('ix_facturas_status_pago', 'facturas', ['status_pago'], unique=False)
    op.create_table('facturas_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('producto_servicio_id', sa.UUID(), nullable=True),
    sa.Column('no_identificacion', sa.String(length=50), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('clave_producto', sa.String(length=20), nullable=False),
    sa.Column('clave_unidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('objeto_imp', sa.String(length=2), nullable=True),
    sa.Column('base_iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iva_tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('iva_tasa', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('iva_importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ret_iva_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ret_iva_tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('ret_iva_tasa', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ret_iva_importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ret_isr_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ret_isr_tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('ret_isr_tasa', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ret_isr_importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ieps_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ieps_tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('ieps_tasa_cuota', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ieps_importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_servicio_id'], ['productos_servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facturas_detalle_claves', 'facturas_detalle', ['clave_producto', 'clave_unidad'], unique=False)
    op.create_index(op.f('ix_facturas_detalle_factura_id'), 'facturas_detalle', ['factura_id'], unique=False)
    op.create_index('ix_facturas_detalle_no_ident', 'facturas_detalle', ['no_identificacion'], unique=False)
    op.create_index(op.f('ix_facturas_detalle_producto_servicio_id'), 'facturas_detalle', ['producto_servicio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_detalle_producto_servicio_id'), table_name='facturas_detalle')
    op.drop_index('ix_facturas_detalle_no_ident', table_name='facturas_detalle')
    op.drop_index(op.f('ix_facturas_detalle_factura_id'), table_name='facturas_detalle')
    op.drop_index('ix_facturas_detalle_claves', table_name='facturas_detalle')
    op.drop_table('facturas_detalle')
    op.drop_index('ix_facturas_status_pago', table_name='facturas')
    op.drop_index('ix_facturas_serie_folio', table_name='facturas')
    op.drop_index('ix_facturas_fechas_pago', table_name='facturas')
    op.drop_index(op.f('ix_facturas_empresa_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_id'), table_name='facturas')
    op.drop_table('facturas')
    # ### end Alembic commands ###
