"""facturas fix

Revision ID: bab7620eed49
Revises: 43c8158dae83
Create Date: 2025-08-12 17:03:14.335887

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bab7620eed49"
down_revision: Union[str, Sequence[str], None] = "43c8158dae83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
