"""add_contacto_table

Revision ID: bb652289eaaf
Revises: 147723f0d03a
Create Date: 2025-10-07 19:44:57.071158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb652289eaaf'
down_revision: Union[str, Sequence[str], None] = '147723f0d03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('ADMINISTRATIVO', 'COBRANZA', 'OPERATIVO', 'PRINCIPAL', 'OTRO', name='tipocontacto'), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactos')
    # ### end Alembic commands ###
