"""add logo to empresa

Revision ID: bf84cfb03f50
Revises: 69d1c4e01ed9
Create Date: 2025-08-19 18:38:03.923844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf84cfb03f50"
down_revision: Union[str, Sequence[str], None] = "69d1c4e01ed9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("empresas", sa.Column("logo", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("empresas", "logo")
    # ### end Alembic commands ###
