"""Add metodo_pago to egresos

Revision ID: bfae11d38d0a
Revises: d1e6db0dc69b
Create Date: 2025-10-03 18:07:27.874333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfae11d38d0a'
down_revision: Union[str, Sequence[str], None] = 'd1e6db0dc69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('metodo_pago', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos', 'metodo_pago')
    # ### end Alembic commands ###
