"""add impuestos_dr to pago_documentos_relacionados

Revision ID: c0d104bf09e0
Revises: bfae11d38d0a
Create Date: 2025-10-03 19:07:19.101116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c0d104bf09e0"
down_revision: Union[str, Sequence[str], None] = "bfae11d38d0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pago_documentos_relacionados",
        sa.Column(
            "impuestos_dr", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pago_documentos_relacionados", "impuestos_dr")
    # ### end Alembic commands ###
