"""feat: add pagos and related tables

Revision ID: c900a60fcd14
Revises: 01639b947ac0
Create Date: 2025-09-16 15:30:08.342980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c900a60fcd14'
down_revision: Union[str, Sequence[str], None] = '01639b947ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('forma_pago_p', sa.String(length=2), nullable=False),
    sa.Column('moneda_p', sa.String(length=3), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tipo_cambio_p', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('estatus', sa.Enum('BORRADOR', 'TIMBRADO', 'CANCELADO', name='estatuspago'), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('fecha_timbrado', sa.DateTime(), nullable=True),
    sa.Column('xml_string', sa.Text(), nullable=True),
    sa.Column('cadena_original', sa.Text(), nullable=True),
    sa.Column('qr_url', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_cliente_id'), 'pagos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pagos_empresa_id'), 'pagos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pagos_uuid'), 'pagos', ['uuid'], unique=True)
    op.create_table('pago_documentos_relacionados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('id_documento', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('folio', sa.String(), nullable=True),
    sa.Column('moneda_dr', sa.String(length=3), nullable=False),
    sa.Column('num_parcialidad', sa.Numeric(precision=10), nullable=False),
    sa.Column('imp_saldo_ant', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('imp_pagado', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('imp_saldo_insoluto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tipo_cambio_dr', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_documentos_relacionados_factura_id'), 'pago_documentos_relacionados', ['factura_id'], unique=False)
    op.create_index(op.f('ix_pago_documentos_relacionados_pago_id'), 'pago_documentos_relacionados', ['pago_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_documentos_relacionados_pago_id'), table_name='pago_documentos_relacionados')
    op.drop_index(op.f('ix_pago_documentos_relacionados_factura_id'), table_name='pago_documentos_relacionados')
    op.drop_table('pago_documentos_relacionados')
    op.drop_index(op.f('ix_pagos_uuid'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_empresa_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_cliente_id'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
