"""Add bank details to Empresa

Revision ID: cfa7eee2e18f
Revises: 2d2bc3db3f3e
Create Date: 2025-12-23 21:11:15.667129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa7eee2e18f'
down_revision: Union[str, Sequence[str], None] = '2d2bc3db3f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('usuario_empresa')
    op.drop_index(op.f('idx_clientes_nombre_comercial'), table_name='clientes')
    op.drop_index(op.f('idx_clientes_razon_social'), table_name='clientes')
    op.drop_index(op.f('idx_clientes_rfc'), table_name='clientes')
    op.create_index('ix_egresos_empresa_id', 'egresos', ['empresa_id'], unique=False)
    op.create_index('ix_egresos_estatus', 'egresos', ['estatus'], unique=False)
    op.create_index('ix_egresos_fecha_egreso', 'egresos', ['fecha_egreso'], unique=False)
    op.add_column('empresas', sa.Column('nombre_banco', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('numero_cuenta', sa.String(length=50), nullable=True))
    op.add_column('empresas', sa.Column('clabe', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('beneficiario', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_factura_creado_en'), table_name='facturas')
    op.drop_index(op.f('idx_factura_fecha_emision'), table_name='facturas')
    op.create_index('ix_facturas_estatus', 'facturas', ['estatus'], unique=False)
    op.create_index('ix_facturas_fecha_emision', 'facturas', ['fecha_emision'], unique=False)
    op.drop_index(op.f('idx_pago_fecha'), table_name='pagos')
    # op.drop_constraint(op.f('uq_presupuestos_folio_version_empresa'), 'presupuestos', type_='unique')
    op.create_unique_constraint(None, 'presupuestos', ['folio'])
    op.drop_index(op.f('idx_prod_clave'), table_name='productos_servicios')
    op.drop_index(op.f('idx_prod_descripcion'), table_name='productos_servicios')
    op.drop_index(op.f('idx_prod_empresa'), table_name='productos_servicios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_prod_empresa'), 'productos_servicios', ['empresa_id'], unique=False)
    op.create_index(op.f('idx_prod_descripcion'), 'productos_servicios', ['descripcion'], unique=False)
    op.create_index(op.f('idx_prod_clave'), 'productos_servicios', ['clave_producto'], unique=False)
    op.drop_constraint(None, 'presupuestos', type_='unique')
    op.create_unique_constraint(op.f('uq_presupuestos_folio_version_empresa'), 'presupuestos', ['folio', 'version', 'empresa_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pago_fecha'), 'pagos', ['fecha_pago'], unique=False)
    op.drop_index('ix_facturas_fecha_emision', table_name='facturas')
    op.drop_index('ix_facturas_estatus', table_name='facturas')
    op.create_index(op.f('idx_factura_fecha_emision'), 'facturas', ['fecha_emision'], unique=False)
    op.create_index(op.f('idx_factura_creado_en'), 'facturas', ['creado_en'], unique=False)
    op.drop_column('empresas', 'beneficiario')
    op.drop_column('empresas', 'clabe')
    op.drop_column('empresas', 'numero_cuenta')
    op.drop_column('empresas', 'nombre_banco')
    op.drop_index('ix_egresos_fecha_egreso', table_name='egresos')
    op.drop_index('ix_egresos_estatus', table_name='egresos')
    op.drop_index('ix_egresos_empresa_id', table_name='egresos')
    op.create_index(op.f('idx_clientes_rfc'), 'clientes', ['rfc'], unique=False)
    op.create_index(op.f('idx_clientes_razon_social'), 'clientes', ['nombre_razon_social'], unique=False)
    op.create_index(op.f('idx_clientes_nombre_comercial'), 'clientes', ['nombre_comercial'], unique=False)
    op.create_table('usuario_empresa',
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('usuario_empresa_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('usuario_empresa_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('usuario_id', 'empresa_id', name=op.f('usuario_empresa_pkey'))
    )
    # ### end Alembic commands ###
