"""add rfc_proveedor_sat to factura

Revision ID: d01934cde1b6
Revises: 0cc037e247c8
Create Date: 2025-08-24 13:33:18.333808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d01934cde1b6"
down_revision: Union[str, Sequence[str], None] = "0cc037e247c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facturas", sa.Column("rfc_proveedor_sat", sa.String(length=13), nullable=True)
    )
    op.alter_column(
        "facturas", "fecha_emision", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facturas",
        "fecha_emision",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("facturas", "rfc_proveedor_sat")
    # ### end Alembic commands ###
