"""Agregar tabla de egresos

Revision ID: d1e6db0dc69b
Revises: 750321b499f4
Create Date: 2025-09-29 08:20:52.284753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e6db0dc69b'
down_revision: Union[str, Sequence[str], None] = '750321b499f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egresos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Enum('GASTOS_GENERALES', 'COMPRAS', 'SERVICIOS', 'IMPUESTOS', 'NOMINA', 'ALQUILER_OFICINA', 'MARKETING_PUBLICIDAD', 'TELECOMUNICACIONES', 'TRANSPORTE_VIAJES', 'SEGUROS', 'REPARACIONES_MANTENIMIENTO', 'SUMINISTROS_OFICINA', 'SERVICIOS_PROFESIONALES', 'LICENCIAS_SOFTWARE', 'CAPACITACION', 'GASOLINA', 'OTROS', name='categoriaegreso'), nullable=False),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'PAGADO', 'CANCELADO', name='estatusegreso'), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=True),
    sa.Column('path_documento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egresos')
    # ### end Alembic commands ###
