"""fix: update pagos table with path columns

Revision ID: f00a9666ab86
Revises: c900a60fcd14
Create Date: 2025-09-16 15:31:02.809369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00a9666ab86'
down_revision: Union[str, Sequence[str], None] = 'c900a60fcd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('xml_path', sa.String(length=255), nullable=True))
    op.add_column('pagos', sa.Column('pdf_path', sa.String(length=255), nullable=True))
    op.drop_column('pagos', 'xml_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('xml_string', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pagos', 'pdf_path')
    op.drop_column('pagos', 'xml_path')
    # ### end Alembic commands ###
