"""add_cobranza_module

Revision ID: f51db8305cba
Revises: 97ee9120af15
Create Date: 2026-01-16 05:20:29.957160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51db8305cba'
down_revision: Union[str, Sequence[str], None] = '97ee9120af15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobranza_notas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('fecha_promesa_pago', sa.DateTime(), nullable=True),
    sa.Column('creado_po', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_po'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobranza_notas_cliente_id'), 'cobranza_notas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cobranza_notas_empresa_id'), 'cobranza_notas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cobranza_notas_factura_id'), 'cobranza_notas', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cobranza_notas_factura_id'), table_name='cobranza_notas')
    op.drop_index(op.f('ix_cobranza_notas_empresa_id'), table_name='cobranza_notas')
    op.drop_index(op.f('ix_cobranza_notas_cliente_id'), table_name='cobranza_notas')
    op.drop_table('cobranza_notas')
    # ### end Alembic commands ###
