from typing import List, Dict

"""
Catálogo generado a partir de la hoja 'c_Moneda'
"""

CATALOGO: List[Dict[str, str]] = [
    {"clave": "AED", "descripcion": "Dirham de EAU"},
    {"clave": "AFN", "descripcion": "Afghani"},
    {"clave": "ALL", "descripcion": "Lek"},
    {"clave": "AMD", "descripcion": "Dram armenio"},
    {"clave": "ANG", "descripcion": "Florín antillano neerlandés"},
    {"clave": "AOA", "descripcion": "Kwanza"},
    {"clave": "ARS", "descripcion": "Peso Argentino"},
    {"clave": "AUD", "descripcion": "Dólar Australiano"},
    {"clave": "AWG", "descripcion": "Aruba Florin"},
    {"clave": "AZN", "descripcion": "Azerbaijanian Manat"},
    {"clave": "BAM", "descripcion": "Convertibles marca"},
    {"clave": "BBD", "descripcion": "Dólar de Barbados"},
    {"clave": "BDT", "descripcion": "Taka"},
    {"clave": "BGN", "descripcion": "Lev búlgaro"},
    {"clave": "BHD", "descripcion": "Dinar de Bahrein"},
    {"clave": "BIF", "descripcion": "Burundi Franc"},
    {"clave": "BMD", "descripcion": "Dólar de Bermudas"},
    {"clave": "BND", "descripcion": "Dólar de Brunei"},
    {"clave": "BOB", "descripcion": "Boliviano"},
    {"clave": "BOV", "descripcion": "Mvdol"},
    {"clave": "BRL", "descripcion": "Real brasileño"},
    {"clave": "BSD", "descripcion": "Dólar de las Bahamas"},
    {"clave": "BTN", "descripcion": "Ngultrum"},
    {"clave": "BWP", "descripcion": "Pula"},
    {"clave": "BYR", "descripcion": "Rublo bielorruso"},
    {"clave": "BZD", "descripcion": "Dólar de Belice"},
    {"clave": "CAD", "descripcion": "Dólar Canadiense"},
    {"clave": "CDF", "descripcion": "Franco congoleño"},
    {"clave": "CHE", "descripcion": "WIR Euro"},
    {"clave": "CHF", "descripcion": "Franco Suizo"},
    {"clave": "CHW", "descripcion": "Franc WIR"},
    {"clave": "CLF", "descripcion": "Unidad de Fomento"},
    {"clave": "CLP", "descripcion": "Peso chileno"},
    {"clave": "CNH", "descripcion": "Yuan extracontinental (China )"},
    {"clave": "CNY", "descripcion": "Yuan Renminbi"},
    {"clave": "COP", "descripcion": "Peso Colombiano"},
    {"clave": "COU", "descripcion": "Unidad de Valor real"},
    {"clave": "CRC", "descripcion": "Colón costarricense"},
    {"clave": "CUC", "descripcion": "Peso Convertible"},
    {"clave": "CUP", "descripcion": "Peso Cubano"},
    {"clave": "CVE", "descripcion": "Cabo Verde Escudo"},
    {"clave": "CZK", "descripcion": "Corona checa"},
    {"clave": "DJF", "descripcion": "Franco de Djibouti"},
    {"clave": "DKK", "descripcion": "Corona danesa"},
    {"clave": "DOP", "descripcion": "Peso Dominicano"},
    {"clave": "DZD", "descripcion": "Dinar argelino"},
    {"clave": "EGP", "descripcion": "Libra egipcia"},
    {"clave": "ERN", "descripcion": "Nakfa"},
    {"clave": "ESD", "descripcion": "Dólar de Ecuador"},
    {"clave": "ETB", "descripcion": "Birr etíope"},
    {"clave": "EUR", "descripcion": "Euro"},
    {"clave": "FJD", "descripcion": "Dólar de Fiji"},
    {"clave": "FKP", "descripcion": "Libra malvinense"},
    {"clave": "GBP", "descripcion": "Libra Esterlina"},
    {"clave": "GEL", "descripcion": "Lari"},
    {"clave": "GHS", "descripcion": "Cedi de Ghana"},
    {"clave": "GIP", "descripcion": "Libra de Gibraltar"},
    {"clave": "GMD", "descripcion": "Dalasi"},
    {"clave": "GNF", "descripcion": "Franco guineano"},
    {"clave": "GTQ", "descripcion": "Quetzal"},
    {"clave": "GYD", "descripcion": "Dólar guyanés"},
    {"clave": "HKD", "descripcion": "Dólar De Hong Kong"},
    {"clave": "HNL", "descripcion": "Lempira"},
    {"clave": "HRK", "descripcion": "Kuna"},
    {"clave": "HTG", "descripcion": "Gourde"},
    {"clave": "HUF", "descripcion": "Florín"},
    {"clave": "IDR", "descripcion": "Rupia"},
    {"clave": "ILS", "descripcion": "Nuevo Shekel Israelí"},
    {"clave": "INR", "descripcion": "Rupia india"},
    {"clave": "IQD", "descripcion": "Dinar iraquí"},
    {"clave": "IRR", "descripcion": "Rial iraní"},
    {"clave": "ISK", "descripcion": "Corona islandesa"},
    {"clave": "JMD", "descripcion": "Dólar Jamaiquino"},
    {"clave": "JOD", "descripcion": "Dinar jordano"},
    {"clave": "JPY", "descripcion": "Yen"},
    {"clave": "KES", "descripcion": "Chelín keniano"},
    {"clave": "KGS", "descripcion": "Som"},
    {"clave": "KHR", "descripcion": "Riel"},
    {"clave": "KMF", "descripcion": "Franco Comoro"},
    {"clave": "KPW", "descripcion": "Corea del Norte ganó"},
    {"clave": "KRW", "descripcion": "Won"},
    {"clave": "KWD", "descripcion": "Dinar kuwaití"},
    {"clave": "KYD", "descripcion": "Dólar de las Islas Caimán"},
    {"clave": "KZT", "descripcion": "Tenge"},
    {"clave": "LAK", "descripcion": "Kip"},
    {"clave": "LBP", "descripcion": "Libra libanesa"},
    {"clave": "LKR", "descripcion": "Rupia de Sri Lanka"},
    {"clave": "LRD", "descripcion": "Dólar liberiano"},
    {"clave": "LSL", "descripcion": "Loti"},
    {"clave": "LYD", "descripcion": "Dinar libio"},
    {"clave": "MAD", "descripcion": "Dirham marroquí"},
    {"clave": "MDL", "descripcion": "Leu moldavo"},
    {"clave": "MGA", "descripcion": "Ariary malgache"},
    {"clave": "MKD", "descripcion": "Denar"},
    {"clave": "MMK", "descripcion": "Kyat"},
    {"clave": "MNT", "descripcion": "Tugrik"},
    {"clave": "MOP", "descripcion": "Pataca"},
    {"clave": "MRO", "descripcion": "Ouguiya"},
    {"clave": "MUR", "descripcion": "Rupia de Mauricio"},
    {"clave": "MVR", "descripcion": "Rupia"},
    {"clave": "MWK", "descripcion": "Kwacha"},
    {"clave": "MXN", "descripcion": "Peso Mexicano"},
    {"clave": "MXV", "descripcion": "México Unidad de Inversión (UDI)"},
    {"clave": "MYR", "descripcion": "Ringgit malayo"},
    {"clave": "MZN", "descripcion": "Mozambique Metical"},
    {"clave": "NAD", "descripcion": "Dólar de Namibia"},
    {"clave": "NGN", "descripcion": "Naira"},
    {"clave": "NIC", "descripcion": "Córdoba (Nicaragua)"},
    {"clave": "NIO", "descripcion": "Córdoba Oro"},
    {"clave": "NOK", "descripcion": "Corona noruega"},
    {"clave": "NPR", "descripcion": "Rupia nepalí"},
    {"clave": "NZD", "descripcion": "Dólar de Nueva Zelanda"},
    {"clave": "OMR", "descripcion": "Rial omaní"},
    {"clave": "PAB", "descripcion": "Balboa"},
    {"clave": "PEN", "descripcion": "Nuevo Sol"},
    {"clave": "PGK", "descripcion": "Kina"},
    {"clave": "PHP", "descripcion": "Peso filipino"},
    {"clave": "PKR", "descripcion": "Rupia de Pakistán"},
    {"clave": "PLN", "descripcion": "Zloty"},
    {"clave": "PYG", "descripcion": "Guaraní"},
    {"clave": "QAR", "descripcion": "Qatar Rial"},
    {"clave": "RON", "descripcion": "Leu rumano"},
    {"clave": "RSD", "descripcion": "Dinar serbio"},
    {"clave": "RUB", "descripcion": "Rublo ruso"},
    {"clave": "RWF", "descripcion": "Franco ruandés"},
    {"clave": "SAR", "descripcion": "Riyal saudí"},
    {"clave": "SBD", "descripcion": "Dólar de las Islas Salomón"},
    {"clave": "SCR", "descripcion": "Rupia de Seychelles"},
    {"clave": "SDG", "descripcion": "Libra sudanesa"},
    {"clave": "SEK", "descripcion": "Corona sueca"},
    {"clave": "SGD", "descripcion": "Dólar De Singapur"},
    {"clave": "SHP", "descripcion": "Libra de Santa Helena"},
    {"clave": "SLL", "descripcion": "Leona"},
    {"clave": "SOS", "descripcion": "Chelín somalí"},
    {"clave": "SRD", "descripcion": "Dólar de Suriname"},
    {"clave": "SSP", "descripcion": "Libra sudanesa Sur"},
    {"clave": "STD", "descripcion": "Dobra"},
    {"clave": "SVC", "descripcion": "Colon El Salvador"},
    {"clave": "SYP", "descripcion": "Libra Siria"},
    {"clave": "SZL", "descripcion": "Lilangeni"},
    {"clave": "THB", "descripcion": "Baht"},
    {"clave": "TJS", "descripcion": "Somoni"},
    {"clave": "TMT", "descripcion": "Turkmenistán nuevo manat"},
    {"clave": "TND", "descripcion": "Dinar tunecino"},
    {"clave": "TOP", "descripcion": "Pa'anga"},
    {"clave": "TRY", "descripcion": "Lira turca"},
    {"clave": "TTD", "descripcion": "Dólar de Trinidad y Tobago"},
    {"clave": "TWD", "descripcion": "Nuevo dólar de Taiwán"},
    {"clave": "TZS", "descripcion": "Shilling tanzano"},
    {"clave": "UAH", "descripcion": "Hryvnia"},
    {"clave": "UGX", "descripcion": "Shilling de Uganda"},
    {"clave": "USD", "descripcion": "Dólar americano"},
    {"clave": "USN", "descripcion": "Dólar estadounidense (día siguiente)"},
    {"clave": "UYI", "descripcion": "Peso Uruguay en Unidades Indexadas (URUIURUI)"},
    {"clave": "UYP", "descripcion": "Uruguay (Peso)"},
    {"clave": "UYU", "descripcion": "Peso Uruguayo"},
    {"clave": "UZS", "descripcion": "Uzbekistán Sum"},
    {"clave": "VEF", "descripcion": "Bolívar"},
    {"clave": "VES", "descripcion": "Bolívar digital  (Venezuela)"},
    {"clave": "VND", "descripcion": "Dong"},
    {"clave": "VUV", "descripcion": "Vatu"},
    {"clave": "WST", "descripcion": "Tala"},
    {"clave": "XAF", "descripcion": "Franco CFA BEAC"},
    {"clave": "XAG", "descripcion": "Plata"},
    {"clave": "XAU", "descripcion": "Oro"},
    {
        "clave": "XBA",
        "descripcion": "Unidad de Mercados de Bonos Unidad Europea Composite (EURCO)",
    },
    {
        "clave": "XBB",
        "descripcion": "Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6)",
    },
    {
        "clave": "XBC",
        "descripcion": "Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9)",
    },
    {
        "clave": "XBD",
        "descripcion": "Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17)",
    },
    {"clave": "XCD", "descripcion": "Dólar del Caribe Oriental"},
    {"clave": "XDR", "descripcion": "DEG (Derechos Especiales de Giro)"},
    {"clave": "XOF", "descripcion": "Franco CFA BCEAO"},
    {"clave": "XPD", "descripcion": "Paladio"},
    {"clave": "XPF", "descripcion": "Franco CFP"},
    {"clave": "XPT", "descripcion": "Platino"},
    {"clave": "XSU", "descripcion": "Sucre"},
    {
        "clave": "XTS",
        "descripcion": "Códigos reservados específicamente para propósitos de prueba",
    },
    {"clave": "XUA", "descripcion": "Unidad ADB de Cuenta"},
    {
        "clave": "XXX",
        "descripcion": "Los códigos asignados para las transacciones en que intervenga ninguna moneda",
    },
    {"clave": "YER", "descripcion": "Rial yemení"},
    {"clave": "ZAR", "descripcion": "Rand"},
    {"clave": "ZMW", "descripcion": "Kwacha zambiano"},
    {"clave": "ZWL", "descripcion": "Zimbabwe Dólar"},
]
